language: node_js
node_js: "10.15"
cache: yarn

deploy:
  -
    provider: script
    script: bash scripts/deploy-image.sh latest
    on:
      branch: master
  -
    provider: script
    script: bash scripts/deploy-image.sh $TRAVIS_TAG
    on:
      tags: true
