language: node_js
node_js: "10.15"
cache: yarn

services:
  - mongodb
  - elasticsearch

env:
  - MONGO_DSN=mongodb://mongodb:27017
  - TENANT_KEY=as3_baseplatform
  - SERVICE_URL=http://graphql-server
  - ELASTICSEARCH_URL=http://localhost:9200
  - ENABLE_BASEDB_LOGGING=0

deploy:
  -
    provider: script
    script: bash scripts/doc.sh master
    on:
      branch: doc
  # -
  #   provider: script
  #   script: bash scripts/doc.sh $TRAVIS_TAG
  #   on:
  #     tags: true
  # # -
  # #   provider: script
  # #   script: bash scripts/deploy-image.sh latest
  # #   on:
  # #     branch: master
  # -
  #   provider: script
  #   script: bash scripts/deploy-image.sh $TRAVIS_TAG
  #   on:
  #     tags: true
  # -
  #   provider: script
  #   script: bash scripts/deploy-rancher.sh
  #   on:
  #     tags: true
  #     condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
