language: node_js
node_js: "10.13"
cache: yarn
deploy:
  -
    provider: script
    script: bash scripts/deploy/image.sh
    on:
      tags: true
  -
    provider: script
    script: bash scripts/deploy/deploy.sh
    on:
      tags: true
      condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
