language: node_js
node_js: "10.15"
cache: yarn

env:
  - SERVICE=graphql-server
  - SERVICE=rss
  - SERVICE=oembed
  - SERVICE=sitemaps
  - SERVICE=hooks
  - SERVICE=google-data-api

stages:
  - name: test

  - name: production
    if: tag is present

  - name: staging
    # if: branch = "master" AND type != "pull_request"
    if: branch = "staging" AND type != "pull_request"

jobs:
  include:
    - stage: test
      script: scripts/workspace.sh ${SERVICE} test
      env:
        - NODE_ENV=test

    - stage: production
      name: ${SERVICE}
      script: scripts/deploy.js ${SERVICE}
      env:
        - RANCHER_CLUSTERID=c-gxsr7
        - TARGET=production

    - stage: staging
      name: ${SERVICE}
      script: scripts/deploy.js ${SERVICE}
      env:
        - RANCHER_CLUSTERID=c-rc5kp
        - TARGET=staging
