language: node_js
node_js: "10.15"
cache: yarn

env:
  - TARGET=production RANCHER_CLUSTERID=c-gxsr7
  - TARGET=staging RANCHER_CLUSTERID=c-rc5kp

stages:
  - name: test
    if: env(TARGET) = production

  - name: deploy
    if: (env(TARGET) = staging AND tag is present) OR (env(TARGET) = production AND tag =~ /^v\d+\.\d+\.\d+$/)

jobs:
  include:
    - stage: test

    - stage: deploy
      name: Deployment Started
      script: scripts/deploy-notify-start.sh
      install: skip

    #############################
    # vvv ADD SERVICES HERE vvv #
    #############################

    - stage: deploy
      name: GraphQL Server
      script: scripts/deploy.js graphql-server

    - stage: deploy
      name: Sitemaps
      script: scripts/deploy.js sitemaps

    - stage: deploy
      name: RSS
      script: scripts/deploy.js rss

    - stage: deploy
      name: Hooks
      script: scripts/deploy.js hooks

    - stage: deploy
      name: oEmbed
      script: scripts/deploy.js oembed

    - stage: deploy
      name: Google Data API
      script: scripts/deploy.js google-data-api

    #############################
    # ^^^ ADD SERVICES HERE ^^^ #
    #############################

    - stage: deploy
      name: Deployment Ended
      script: scripts/deploy-notify.sh
      install: skip
