language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: notify_start
    if: tag is present
  - name: deploy
    if: tag is present
  - name: notify
    if: tag is present

jobs:
  include:
    - stage: test

    - stage: notify_start
      script: scripts/deploy-notify-start.sh
      install: skip

    - stage: notify
      script: scripts/deploy-notify.sh
      install: skip

    - stage: deploy
      name: GraphQL Server
      script: scripts/deploy.js graphql-server

    # - stage: deploy
    #   name: Manage
    #   script: scripts/deploy.js manage

    - stage: deploy
      name: Sitemaps
      script: scripts/deploy.js sitemaps

    - stage: deploy
      name: RSS
      script: scripts/deploy.js rss

    - stage: deploy
      name: Hooks
      script: scripts/deploy.js hooks

    - stage: deploy
      name: oEmbed
      script: scripts/deploy.js oembed
