version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: base-cms-node-alpine:latest
  build: ./node-alpine-git
  entrypoint: ["node"]
  working_dir: /base-cms
  volumes:
    - .:/base-cms:cached
    - ./node_modules:/base-cms/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    YARN_CACHE_FOLDER: /.yarn-cache
    NODE_ENV: development
    MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
    TENANT_KEY: ${TENANT_KEY}
    SERVICE_URL: ${SERVICE_URL-http://graphql-server}
    ELASTICSEARCH_URL: ${ELASTICSEARCH_URL-http://elasticsearch:9200}
    ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-0}
    APP_PORT: ${APP_PORT}

services:
  commands:
    <<: *node
    working_dir: /base-cms
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "10000:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      server.name: kibana
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL-http://elasticsearch:9200}"
      LOGGING_QUIET: "true"
    ports:
      - "10001:5601"
    depends_on:
      - elasticsearch
  keyword-analysis:
    << : *node
    working_dir: /base-cms/services/keyword-analysis
    command: ["src"]
    depends_on:
      - mongodb
      - elasticsearch
      - kibana
  graphql-server:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    depends_on:
      - mongodb
    ports:
      - "10002:80"
  example-website:
    << : *node
    working_dir: /base-cms/services/example-website
    command: ["server.js"]
    depends_on:
      - graphql-server
    ports:
      - "10003:80"

volumes:
  esdata: {}
  mongodb: {}
  yarn-cache: {}
