version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /base-cms
  volumes:
    - .:/base-cms:cached
    - ./node_modules:/base-cms/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    YARN_CACHE_FOLDER: /.yarn-cache
    NODE_ENV: development
    MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
    TENANT_KEY: ${TENANT_KEY}
    SERVICE_URL: ${SERVICE_URL-http://graphql-server}
    ELASTICSEARCH_URL: ${ELASTICSEARCH_URL-http://elasticsearch:9200}
    ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-0}

services:
  commands:
    <<: *node
    working_dir: /base-cms
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "10000:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      server.name: kibana
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL-http://elasticsearch:9200}"
      LOGGING_QUIET: "true"
    ports:
      - "10001:5601"
    depends_on:
      - elasticsearch
  keyword-analysis:
    << : *node
    working_dir: /base-cms/services/keyword-analysis
    command: ["src"]
    depends_on:
      - mongodb
      - elasticsearch
      - kibana
  graphql-server:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    depends_on:
      - mongodb
    ports:
      - "10002:80"
  nextjs-example-website:
    << : *node
    working_dir: /base-cms/services/nextjs-example-website
    command: ["server.js"]
    depends_on:
      - graphql-server
    ports:
      - "10003:80"
  express-example-website:
    << : *node
    working_dir: /base-cms/services/express-example-website
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      YARN_CACHE_FOLDER: /.yarn-cache
      NODE_ENV: development
      GRAPHQL_URI: ${GRAPHQL_URI-http://graphql-server}
      INTERNAL_PORT: ${INTERNAL_PORT-80}
      EXTERNAL_PORT: ${EXTERNAL_PORT-10006}
    depends_on:
      - graphql-server
    ports:
      - "${EXTERNAL_PORT-10006}:${INTERNAL_PORT-80}"
  manage:
    <<: *node
    image: danlynn/ember-cli:3.7.1
    working_dir: /base-cms/services/manage
    entrypoint: ["node_modules/.bin/ember"]
    command: ["serve", "--port", "10004", "--proxy", "http://graphql-server"]
    depends_on:
      - graphql-server
    ports:
      - "10004:10004" # serve port
      - "10005:10005" # test port (needs to be configured)

volumes:
  esdata: {}
  mongodb: {}
  yarn-cache: {}
