version: '3.7'

x-service-defaults:
  &service-defaults
  tty: true
  init: true
  image: node:10.13-alpine
  command: ['/base-cms/node_modules/.bin/gulp']
  volumes:
    - .:/base-cms:cached
    - node_modules:/base-cms/node_modules
  environment:
    NODE_ENV: development
    NATS_DSN: nats://nats:4222
    MONGO_DSN: mongodb://mongodb:27017
    ELASTICSEARCH_URL: http://elasticsearch:9200

services:
  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "10000:27017"
  nats:
    image: nats:latest
    ports:
      - "10001:8222"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      server.name: kibana
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL-http://elasticsearch:9200}"
      LOGGING_QUIET: "true"
    ports:
      - "10002:5601"
    depends_on:
      - elasticsearch
  db:
    << : *service-defaults
    working_dir: /base-cms/services/db
    depends_on:
      - mongodb
      - nats
  keyword-analysis:
    << : *service-defaults
    working_dir: /base-cms/services/keyword-analysis
    command: ['node', 'src']
    depends_on:
      - db
      - elasticsearch
      - kibana
  graphql-server-express:
    << : *service-defaults
    working_dir: /base-cms/services/graphql-server-express
    depends_on:
      - db
    ports:
      - "6915:80"

volumes:
  esdata: {}
  node_modules: {}
  mongodb: {}
