version: '3.7'
networks:
  basecms:
      name: basecms
services:
  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "${BASECMS_MONGODB_PORT-10500}:27017"
  nats:
    image: nats:latest
    ports:
      - "${BASECMS_NATS_PORT-8222}:8222"
  db-service:
    tty: true
    init: true
    image: node:10.13-alpine
    working_dir: /base-cms/packages/db-service
    depends_on:
      - mongodb
      - nats
    command: ['/base-cms/node_modules/.bin/gulp']
    volumes:
      - .:/base-cms:cached
      - node_modules:/base-cms/node_modules
  keyword-analysis:
    tty: true
    image: node:10.13-alpine
    working_dir: /base-cms/packages/keyword-analysis
    entrypoint: node src/import
    volumes:
      - .:/base-cms:cached
      - node_modules:/base-cms/node_modules
volumes:
  node_modules: {}
  mongodb: {}
