version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-env-newrelic: &env-newrelic
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-mongo: &env-mongo
  MONGO_DSN: ${MONGO_DSN-mongodb://mongodb:27017}
  ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-0}

x-env-elastic: &env-elastic
  ELASTICSEARCH_URL: ${ELASTICSEARCH_URL-http://elasticsearch:9200}

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /base-cms
  volumes:
    - .:/base-cms:cached
    - ./node_modules:/base-cms/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /base-cms
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "10000:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      server.name: kibana
      ELASTICSEARCH_URL: "${ELASTICSEARCH_URL-http://elasticsearch:9200}"
      LOGGING_QUIET: "true"
    depends_on:
      - elasticsearch
    ports:
      - "10001:5601"

  keyword-analysis:
    << : *node
    working_dir: /base-cms/services/keyword-analysis
    command: ["src"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      <<: *env-elastic
    depends_on:
      - mongodb
      - elasticsearch
      - kibana

  graphql-server:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
    depends_on:
      - mongodb
    ports:
      - "10002:80"

  graphql-server-lfw:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      MONGO_DSN: ${LFW_MONGO_DSN-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
    depends_on:
      - mongodb

  example-laserfocusworld:
    <<: *node
    working_dir: /base-cms/services/example-laserfocusworld
    command: ["/base-cms/node_modules/.bin/basecms-website", "dev", "index.js"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 11162
      LIVERELOAD_PORT: 25162
      TENANT_KEY: ebm_lfw
      GRAPHQL_URI: http://graphql-server-lfw
      SITEMAPS_URI: http://sitemaps
      RSS_URI: http://rss
      OEMBED_URI: http://oembed
      CDN_IMAGE_HOSTNAME: img.laserfocusworld.com
      CDN_ASSET_HOSTNAME: cdn.laserfocusworld.com
      NEW_RELIC_ENABLED: 0
      NEW_RELIC_LICENSE_KEY: (unset)
    depends_on:
      - graphql-server-lfw
      - sitemaps
      - rss
      - oembed
    ports:
      - "11162:80"
      - "25162:25162"

  graphql-server-bzb:
    << : *node
    working_dir: /base-cms/services/graphql-server
    entrypoint: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      MONGO_DSN: ${BZB_MONGO_DSN-mongodb://mongodb:27017}
      ENABLE_BASEDB_LOGGING: ${ENABLE_BASEDB_LOGGING-}
      ENGINE_API_KEY: ${ENGINE_API_KEY-(unset)}
    depends_on:
      - mongodb

  example-bizbash:
    <<: *node
    working_dir: /base-cms/services/example-bizbash
    command: ["/base-cms/node_modules/.bin/basecms-website", "dev", "index.js"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 11163
      LIVERELOAD_PORT: 25163
      TENANT_KEY: bizbash_bzb
      GRAPHQL_URI: http://graphql-server-bzb
      SITEMAPS_URI: http://sitemaps
      RSS_URI: http://rss
      OEMBED_URI: http://oembed
      CDN_IMAGE_HOSTNAME: img.bizbash.com
      CDN_ASSET_HOSTNAME: cdn.bizbash.com
      NEW_RELIC_ENABLED: 0
      NEW_RELIC_LICENSE_KEY: (unset)
    depends_on:
      - graphql-server-bzb
      - sitemaps
      - rss
      - oembed
    ports:
      - "11163:80"
      - "25163:25163"

  haproxy:
    image: haproxy:alpine
    ports: [ "${PORT-10010}:80" ]
    volumes:
      - ./services/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - example-laserfocusworld
      - graphql-server

  sitemaps:
    << : *node
    working_dir: /base-cms/services/sitemaps
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
    depends_on:
      - mongodb
    ports:
      - "10009:80"

  rss:
    << : *node
    working_dir: /base-cms/services/rss
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
    depends_on:
      - mongodb
    ports:
      - "10011:80"

  hooks:
    << : *node
    working_dir: /base-cms/services/hooks
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-mongo
      <<: *env-newrelic
      CAPRICA_DSN: ${CAPRICA_DSN-mongodb://mongodb:27017}
      AERILON_DSN: ${AERILON_DSN-mongodb://mongodb:27017}
      PICON_DSN: ${PICON_DSN-mongodb://mongodb:27017}
    depends_on:
      - mongodb
    ports:
      - "10012:80"

  oembed:
    << : *node
    working_dir: /base-cms/services/oembed
    command: ["/base-cms/node_modules/.bin/gulp"]
    environment:
      <<: *env
      <<: *env-newrelic
      EMBEDLY_API_KEY: ${EMBEDLY_API_KEY}
    ports:
      - "10013:80"

volumes:
  esdata: {}
  mongodb: {}
  yarn-cache: {}
