version: '3.7'

x-service-defaults:
  &service-defaults
  tty: true
  init: true
  image: node:10.13-alpine
  command: ['/base-cms/node_modules/.bin/gulp']
  volumes:
    - .:/base-cms:cached
    - node_modules:/base-cms/node_modules

services:
  mongodb:
    tty: true
    image: mongo:3.4
    volumes:
      - mongodb:/data/db
    ports:
      - "${BASECMS_MONGODB_PORT-10500}:27017"
  nats:
    image: nats:latest
    ports:
      - "${BASECMS_NATS_PORT-8222}:8222"
  db-service:
    << : *service-defaults
    working_dir: /base-cms/packages/db-service
    depends_on:
      - mongodb
      - nats
    environment:
      BASECMS_MONGODB_URL: mongodb://mongodb:27017
      NATS_DSN: nats://nats:4222
  keyword-analysis:
    << : *service-defaults
    working_dir: /base-cms/packages/keyword-analysis
    command: ['node', 'src/import']
  graphql-server-express:
    << : *service-defaults
    working_dir: /base-cms/packages/graphql-server-express
    depends_on:
      - nats
      - db-service
    environment:
      BASECMS_GRAPHQL_PORT: "${BASECMS_GRAPHQL_PORT-6915}"
      BASECMS_GRAPHQL_HOST: 0.0.0.0
      NATS_DSN: nats://nats:4222

volumes:
  node_modules: {}
  mongodb: {}
