version: '3.7'
services:
  keyword-analysis:
    depends_on:
      - elasticsearch
      - kibana
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "${CONTENT_INDEX_ES_PORT-8501}:9200"
      - "${CONTENT_INDEX_TRANSPORT_PORT-8502}:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.2
    environment:
      - server.name=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - LOGGING_QUIET=true
    ports:
      - "${CONTENT_INDEX_KIBANA_PORT-8503}:5601"
    depends_on:
      - elasticsearch
volumes:
  esdata: {}
